pladata-encore/DA36-final-web-BreadScanso-repo

menu/urls.py
menu/views.py
static/css/style.css
static/js/menu_main_best10.js
templates/menu/menu_main.html
templates/menu/menu_main_bread.html
templates/menu/menu_main_dessert.html
templates/menu/menu_store.html

Feat: menu url & views 관리자 메뉴관리 경로 추가 설정 및 메인 전체, 빵, 디저트, 관리자 메뉴관리 html 생성
update: css carousel 기능 추가, js 자동 슬라이드 및 버튼 기능 구현, html 메뉴 메인 전체 best10 구성

Feat: menu url & views 관리자 메뉴관리 경로 추가 설정 및 메인 전체, 빵, 디저트, 관리자 메뉴관리 html 생성

---

breadscanco/urls.py
main/models.py
main/urls.py
main/views.py
static/js/signup.js
templates/main/index.html
templates/main/login.html
templates/main/signup.html

로그인/회원가입 95% 작업 완
- 확인버튼 -> 홈 돌아가기 추가 필요
로그인/회원가입 관련 추가 파일 생성
- static/js/sign.js
- main/urls.py

Update: 로그인/회원가입 95% 작업 완 및 추가 파일 생성

---

templates/layout/member/base_member.html
templates/layout/member/header_member.html
templates/layout/member/sidebar_member.html
templates/layout/store/base_store.html
templates/layout/store/header_store.html
templates/layout/store/sidebar_store.html

본문 내용 화면 중앙 정렬 기능을 sidebar에 포함시킴.

Update: layout update

---

templates/layout/member/member_all_base.html
templates/layout/member/sidebar_member.html
templates/layout/store/sidebar_store.html
templates/layout/store/store_all_base.html

layout 사이드바에 있는 메뉴 중에서 하위 메뉴가 없는 토글 버튼은 링크 삽입 위치가 달라서 수정/추가했음.

update: layout의 sidebar 토글 버튼 링크 삽입 공간 추가

---

menu/urls.py
menu/views.py
static/js/menu_new_menu.js
static/js/menu_store.js
templates/menu/menu_edit.html
templates/menu/menu_info.html
templates/menu/menu_main.html
templates/menu/menu_store.html
templates/menu/new_menu.html

update: 점주 신규 메뉴 등록 페이지, 메뉴 관리 상세 페이지, 메뉴관리 수정 페이지 구성

---

static/js/menu_menu_info.js
static/js/menu_store_main.js
static/js/store_home_edit.js
store/urls.py
store/views.py
templates/menu/menu_info.html
templates/menu/menu_store.html
templates/menu/new_menu.html
templates/store/about_breadscanso_edit.html
templates/store/community_notice.html
templates/store/community_qna.html
templates/store/event_edit.html
templates/store/store_account.html
templates/store/store_home_edit.html
templates/store/store_map.html

update: 관리자 메뉴 상세 정보, 메뉴 관리 페이지, 신규 등록 페이지 기능 각 버튼 기능 추가

feat: store 홈 화면 수정, 브랜드 소개, 매장 안내, 이벤트, 커뮤니티 (공지사항, qna), 매장 정보 url 생성

---

stock/urls.py
stock/views.py
templates/layout/store/base_store.html
templates/stock/stock_ingredient.html
templates/stock/stock_ingredient_edit.html
templates/stock/stock_ingredient_new.html
templates/stock/stock_product.html
templates/stock/stock_product_edit.html
templates/stock/stock_product_new.html

Feat: 제품정고 (재고, 재료) url 생성 및 base_store layout 링크 설정

Feat: 제품정고 (재고, 재료) url 생성 및 base_store layout 링크 설정

---

templates/layout/main/header_main.html
templates/layout/store/base_store.html

update: namespace url 추가.

---

templates/layout/main/header_main.html
templates/layout/member/base_member.html
templates/layout/store/base_store.html
templates/main/index.html
templates/main/login.html
templates/main/signup.html
templates/member/member_delete.html
templates/member/member_delete_detail.html
templates/member/member_edit.html
templates/member/member_page.html
templates/member/member_pw.html
templates/member/member_store.html

예시) 기존 {% url 'member_page' %}  -> {% url 'member:member_page' %}로 namespace로 인한 변경

Add: member namespace 추가로 인한 코드 내 url쪽 코드 추가

---

templates/main/signup.html

- singup crud 작업하면서 기존에 jjungah님이 기존에 만들어둔 일부 코드가 임시로 주석 처리됐었음.
- 이메일 도메인 선택, 연령대&성별 드롭다운, 프로필사진 코드 주석 해제해서 다시 추가.
- 추가된 코드에도 crud 작업할 예정

Fix: singup.html 기존 코드 일부 삽입

---

menu/urls.py
menu/views.py
static/js/menu_main.js
static/js/menu_new_menu.js
static/js/menu_store_main.js
templates/menu/menu_main.html
templates/menu/menu_store.html
templates/menu/new_menu.html
templates/menu/product_detail.html

update: 소비자 메뉴 페이지 검색 기능 추가 및 스타일 조정, menu_store 메인 페이지 수정 및 버튼 기능 추가 메뉴 신규 등록 db 에 밀어넣기 (진행중)

update: 소비자 메뉴 페이지 검색 기능 추가 및 스타일 조정, menu_store 메인 페이지 수정 및 버튼 기능 추가 메뉴 신규 등록 db 에 밀어넣기 (진행중)

---

main/utils.py
main/views.py
menu/utils.py
menu/views.py
static/js/menu_new_menu.js
templates/menu/menu_edit.html

- 관리자 로그인 후 매장페이지에서 신규등록/수정 시 image s3 업로드 및 menu_item 테이블에 링크 저장

Update : menu 신규등록/수정 image 기능 업데이트(S3)

---

menu/views.py
static/js/menu_new_menu.js
static/js/menu_store_main.js
templates/menu/menu_store.html

fix: new_menu 취소 버튼 클릭시 url 이동 경로 해결

update: 점주 매장별로 메뉴 확인 가능 pagination 기능 추가

---

templates/menu/menu_edit.html

Fix : 수정버튼 오류 해결 (모달을 form 안에 넣고 버튼 type을 submit으로 변경)

---

pay/views.py
templates/pay/pay_cancel.html
templates/pay/pay_details.html
templates/pay/pay_main.html

1) 구매/취소내역 - 컬럼&값 추가, 수정
2) 취소내역 - 컬럼&값 추가, 수정
3) 상세내역 - 영수증 컬럼&값 추가, 수정, 배치 조정

Update: 매장페이지 | PAY

---

pay/views.py
templates/pay/pay_main.html

Feat: 매장페이지 | PAY - 결제수단 토글 버튼(카드, 간편결제)

---

pay/views.py
templates/pay/pay_details.html
templates/pay/pay_main.html

- 결제 취소 건은 clickable한 결제일자 버튼을 빨간색으로 표시
- 버튼 색상, 위치 등 css 작업

Feat: 취소 건 표시,  css 작업

---

pay/views.py
static/js/pay_cancel.js
static/js/pay_main.js
templates/pay/pay_cancel.html

- 결제수단(드롭다운) 선택 시 '카드', '간편결제' 필터링 기능 추가
- 페이지네이션 추가
- 결제일시(누르면 상세페이지 이동) 빨간색 버튼으로 변경, 기타 버튼 구성&위치 조정

Feat: 매장페이지 | PAY - 취소내역 기능 추가

---

pay/urls.py
pay/views.py
static/js/pay_member.js
static/js/pay_member_cancel.js
templates/pay/pay_member.html
templates/pay/pay_member_cancel.html
templates/pay/pay_member_details.html

Feat: 마이페이지 - 결제내역, 취소내역, 전자영수증 페이지 기능 모두 구현 완료

---

templates/pay/pay_details.html
templates/pay/pay_main.html

Fix: 매장페이지 - 결제관리 css 수정

---

templates/menu/menu_add.html

fix: 메뉴 신규등록 매장정보 스타일 수정

---

member/urls.py
member/views.py
static/js/member-edit.js
templates/main/signup.html
templates/member/member_edit.html

- 외래키 참조로 인해 member_member 테이블에는 저장되지 않고, auth_user에만 저장되고 있던 문제 해결 (행 삭제 후 새로운 정보 업데이트하는 방법)
- js, html, views 일부 코드 수정 -> AJAX 기능 추가 및 중복버튼 에러 상황 해결

Update: 회원정보수정 - DB 저장 에러 해결, AJAX 추가, 중복버튼 에러 해결

---

member/views.py

- 회원정보 수정 시 member_id(기본키) 변경 문제가 발생
- 기존 구현에서는 member_id를 변경할 때 Member 객체를 삭제하고 새로 생성하는 방식 사용
- 이로 인해 member_id를 외래 키로 참조하는 다른 테이블(결제 내역 등)과의 연결이 끊어지는 문제 발생
- 오류 메시지: "Duplicate entry '10' for key 'member_member.user_id'"
- 위 작업을 이 작업은 Member 모델을 참조하는 모든 테이블에 적용했음
```
#기존의 제약조건 삭제
ALTER TABLE member_qna; (앱명_테이블명)
DROP FOREIGN KEY member_qna_member_id_3c9e0fd6_fk; (제약조건: SHOW CFEATE TABLE member_qna 에서 확인 가능)
ALTER TABLE member_qna
ADD CONSTRAINT member_qna_member_id_2cd447ec_fk
FOREIGN KEY (member_id) REFERENCES member_member(member_id)
ON DELETE SET NULL
ON UPDATE CASCADE;
```
- 기존의 삭제 후 재생성 방식 대신 update() 메서드를 사용하여 기본 키 변경
- ```Member.objects.filter(member_id=current_member_id).update(member_id=new_user_id)```
- 이제 삭제 후 새로 생성이 아니므로, 필요없는 member 값은 삭제 처리

update : 회원정보 수정 방법 행 삭제 -> 업데이트로 변경

---

menu/urls.py
menu/utils.py
menu/views.py
static/js/menu_new_menu_learn.js
templates/menu/new_menu_learn.html
templates/store/store_main_map.html

zip 파일은 이미지 및 동영상 있는 zip 파일만 업로드 가능하게 필터 적용

feat: 신 메뉴 학습시 이미지 여러장 업로드 & zip 파일 업로드 기능 추가
